# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3211f6db1dd969f41c6e65e07e3ccd32b3aa8d3ab7166e00b5417606e41693e26d675604e91175a7b01bfce515c5d61e8af987fc3fd14d155af943df81ad10

test:
  secret_key_base: 3ccfede898939ee54d1145b482e790dd7348653714348a0a6ee72be571f6a12cf140875a01a33591578727d342b80f72ddfe083f267984d8ee59c43e80cc7935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
